"""GhostForge consensus and ordering algorithms.

This module contains research implementations of block colouring, scoring, tip selection, and ordering variants evaluated during the PhD research."""

import networkx as nx
from DAG.dag_helpers import anticone, past, tips
import hashlib


def initialize_genesis(dag, blue_set, blue_scores):
    """Initialize the Genesis block."""
    dag.add_node('G')  # Add Genesis block to DAG
    blue_set.add('G')  # Add Genesis block to the blue set
    blue_scores['G'] = 1  # Set the initial score for the Genesis block

def detect_conflict(dag, block, blue_set, miner_id):
    """Check if the block conflicts with any other block generated by the same miner."""
    block_parents = set(dag.predecessors(block))

    for node in dag.nodes:
        # Check if the node was generated by the same miner and has the same parents
        if node != block and node.startswith(miner_id) and set(dag.predecessors(node)) == block_parents:
            return node  # Return the conflicting block
    return None


def purge_conflicting_blocks(dag, block_to_keep, conflicting_block, blue_set, blue_scores):
    """Remove the conflicting block and its descendants from the blue set."""
    # Remove descendants of the conflicting block
    descendants = nx.descendants(dag, conflicting_block)
    for descendant in descendants:
        if descendant in blue_set:
            blue_set.remove(descendant)
            del blue_scores[descendant]  # Also remove from scores

    # Remove the conflicting block itself
    if conflicting_block in blue_set:
        blue_set.remove(conflicting_block)
        del blue_scores[conflicting_block]
    if conflicting_block in dag.nodes:
        dag.remove_node(conflicting_block)


def handle_conflict(dag, new_block, conflicting_block, blue_set, blue_scores):
    """Handle the conflict by not adding the new block if a conflict is detected."""
    # Simply do not add the new block to the DAG if a conflict is detected
    if conflicting_block:
        print(f"Conflict detected between {new_block} and {conflicting_block}. Keeping {conflicting_block}.")
        # No need to add the new block or update the blue set and scores
        return False  # Indicate that the block was not added
    return True  # Indicate that the block can be added


def dynamic_k_parameter(dag, k_base):
    """Dynamically adjust the K-parameter based on DAG conditions."""
    # Example: increase K if the DAG has grown significantly
    dag_size = len(dag.nodes)
    return max(k_base, int(dag_size / 100))  # Increase K as the DAG grows


def block_level_coloring_and_scoring(dag, block, red_set, blue_set, blue_scores, k, visualizer, miner_id):
    """Block-Level Coloring and Scoring."""
    # print(f"BLOCK LEVEL COLORING AND SCORING")
    if block == 'G':
        return "blue", blue_scores['G']

    inherited_blue_set = set()  # Blue set inherited from the highest scoring parent
    additional_blue_set = set()  # To track additional parents added to the blue set for scoring purposes
    max_score_parent = None  # Parent with the highest blue score
    max_score = -1  # Initialize maximum score to a value that any valid score will exceed


    # Determine the parent with the maximum blue score
    for parent in dag.predecessors(block):
        parent_past = past(dag, parent)  # Retrieve past set of the parent
        if not parent_past:
            parent_past = {parent}  # If the parent past is empty, include the parent itself (Genesis)

        # print(f"Parent: {parent}, Parent Past: {parent_past}")

        # Include the parent itself in the inherited blue set
        current_inherited_set = parent_past.intersection(blue_set) | {parent}
        parent_score = blue_scores.get(parent, 0)  # Get the blue score of the parent

        if parent_score > max_score:
            max_score = parent_score
            max_score_parent = parent
            inherited_blue_set = current_inherited_set  # Update inherited blue set from the parent with the max score

    # Recursive function to check and add to the blue set based on the K condition
    def check_and_add_to_blue_set(parent, inherited_blue_set):
        """Check and add to blue set used by the GhostForge research simulation."""
        blue_anticone = {b for b in anticone(dag, parent) if
                         b in inherited_blue_set}  # Find blue anticone of the parent
        if len(blue_anticone) <= k:
            additional_blue_set.add(parent)  # Add parent to additional blue set if it meets K condition
            inherited_blue_set.add(parent)
            if parent in red_set:
                red_set.remove(parent)
                blue_set.add(parent)
            # Check ancestors of the parent
            for ancestor in dag.predecessors(parent):
                if ancestor not in inherited_blue_set and ancestor not in additional_blue_set:
                    check_and_add_to_blue_set(ancestor, inherited_blue_set)
        else:
            red_set.add(parent)  # Add tip to red set if it doesn't meet K condition
            if parent in blue_set:
                blue_set.remove(parent)
            for ancestor in dag.predecessors(parent):
                if ancestor not in inherited_blue_set and ancestor not in additional_blue_set:
                    check_and_add_to_blue_set(ancestor, inherited_blue_set)

    for parent in dag.predecessors(block):
        if parent != max_score_parent:
            check_and_add_to_blue_set(parent, inherited_blue_set)  # Check other parents

    # Check the block itself
    blue_anticone = {b for b in anticone(dag, block) if b in inherited_blue_set}
    if len(blue_anticone) <= k:
        blue_set.add(block)  # Add block to blue set if it meets K condition
        block_score = len(inherited_blue_set) + 1  # Include the block itself in the score
    else:
        block_score = len(inherited_blue_set)
    # Update the scores of all affected blocks
    def update_block_scores(block, inherited_blue_set):
        """Update block scores used by the GhostForge research simulation."""
        for ancestor in inherited_blue_set:
            if ancestor in blue_set:
                blue_scores[ancestor] = len(past(dag, ancestor).intersection(blue_set)) + 1

    blue_scores[block] = block_score  # Set the blue score of the block
    update_block_scores(block, inherited_blue_set)  # Update scores of all blocks in the inherited blue set

    return "blue" if block in blue_set else "red", block_score


def hash_block(block_id):
    """Calculate the SHA-256 hash of the block ID and return it as an integer."""
    return int(hashlib.sha256(block_id.encode()).hexdigest(), 16)


def block_level_ordering(dag, block, blue_scores):
    """Perform block-level ordering based on current block scores and hash for tie-breaking."""

    def recursive_order(node):
        """Recursively order nodes based on their dependencies and scores."""
        if node == 'G':
            return ['G']

        parents = list(dag.predecessors(node))
        if not parents:
            return [node]

        # # Order parents based on their scores and alphabetically if scores are the same
        # sorted_parents = sorted(parents, key=lambda x: (-blue_scores.get(x, 0), x))
        # Order parents based on their scores and by hash value if scores are the same
        sorted_parents = sorted(parents, key=lambda x: (-blue_scores.get(x, 0), hash_block(x)))

        ordered_blocks = []
        for parent in sorted_parents:
            ordered_blocks.extend(recursive_order(parent))

        # Ensure unique blocks while maintaining order
        ordered_blocks = list(dict.fromkeys(ordered_blocks))
        ordered_blocks.append(node)
        return ordered_blocks

    ordered_list = recursive_order(block)
    # print(f"Block-level ordered list for block {block}: {ordered_list}")
    return ordered_list


def dag_level_coloring_and_ordering(dag, blue_set, red_set, blue_scores, k, previous_order, miner_id, previous_max_tip):
    """DAG-Level Coloring and Ordering."""
    # print(f"DAG LEVEL COLORING AND ORDERING")
    tips_list = list(tips(dag))  # Retrieve the tips of the DAG
    # print(f"TIP LIST: {tips_list}") # Select the tip with the maximum blue score, with a tie-breaker on
    # alphabetical order max_tip = max(tips_list, key=lambda x: (blue_scores.get(x, 0),-ord(x[0]))) # Select the tip
    # with the maximum blue score Select the tip with the maximum blue score, with a tie-breaker based on the
    # smallest hash value
    max_tip = max(tips_list, key=lambda x: (blue_scores.get(x, 0), -hash_block(x)))
    # print(f"Selected Max Tip: {max_tip}")

    # Get blue set of max_tip (blocks that are blue and in the past of max_tip)
    blue_set_of_max_tip = {block for block in past(dag, max_tip) if block in blue_set}
    # print(f"Blue Set of Max Tip: {blue_set_of_max_tip}")

    # Add max_tip to its own blue set
    blue_set_of_max_tip.add(max_tip)
    # print(f"Updated Blue Set of Max Tip (including max_tip): {blue_set_of_max_tip}")

    # Perform the coloring
    inherited_blue_set = set(blue_set_of_max_tip)  # Blue set inherited from the max tip
    additional_blue_set = set(blue_set_of_max_tip)  # To track additional blue blocks added
    red_blocks_order = []  # List to maintain the order of blocks added to the red set

    # print(f"Inherited Blue Set: {inherited_blue_set}")
    # print(f"Initial Additional Blue Set: {additional_blue_set}")

    # Recursive function to check and add tips to the blue set based on the K condition
    def check_and_add_to_blue_set(tip, inherited_blue_set):
        """Check and add to blue set used by the GhostForge research simulation."""
        blue_anticone = {b for b in anticone(dag, tip) if b in inherited_blue_set}
        # print(f"Blue Anticone for tip {tip}: {blue_anticone}")

        if len(blue_anticone) <= k:
            inherited_blue_set.add(tip)  # Add tip to inherited blue set if it meets K condition
            additional_blue_set.add(tip)  # Track newly added blue blocks
            if tip in red_set:
                red_set.remove(tip)
                blue_set.add(tip)  # Remove from red set if it turns blue
                # print(f"Block {tip} removed from Red Set")
            # print(f"Block {tip} added to additional blue set")
            # print(f"Extended blue set to check the anticones: {inherited_blue_set}")

            # Check ancestors of the tip
            for ancestor in dag.predecessors(tip):
                if ancestor not in inherited_blue_set and ancestor not in additional_blue_set:
                    check_and_add_to_blue_set(ancestor, inherited_blue_set)
        else:
            red_set.add(tip)  # Add tip to red set if it doesn't meet K condition
            red_blocks_order.append(tip)  # Keep track of the order in which blocks are added to the red set
            if tip in blue_set:
                blue_set.remove(tip)
            # print(f"Block {tip} added to Red Set (REC)")
            # Check ancestors of the tip
            for ancestor in dag.predecessors(tip):
                if ancestor not in inherited_blue_set and ancestor not in additional_blue_set:
                    check_and_add_to_blue_set(ancestor, inherited_blue_set)

    for tip in tips_list:
        if tip == max_tip:
            continue
        check_and_add_to_blue_set(tip, inherited_blue_set)  # Check other tips

    new_order = inherit_and_determine_order(dag, blue_set, red_set, blue_scores, k, previous_order, tips_list, max_tip,
                                            previous_max_tip)
    print(f"Ordered List for MINER-ID {miner_id}: {new_order}")

    return new_order, inherited_blue_set, max_tip


def inherit_and_determine_order(dag, blue_set, red_set, blue_scores, k, previous_order, tips_list, max_tip,
                                previous_max_tip):
    # print(f"Previous Max tip {previous_max_tip}")
    # Determine the max parent of the max tip
    """Inherit and determine order used by the GhostForge research simulation."""
    parents = list(dag.predecessors(max_tip))
    # max_parent = max(parents, key=lambda x: (blue_scores.get(x, 0), x)) if parents else None
    max_parent = max(parents, key=lambda x: (blue_scores.get(x, 0), hash_block(x))) if parents else None
    # Inherit order up to max_tip if already sorted, otherwise compute it
    if max_tip in previous_order:
        inherited_order = previous_order[:previous_order.index(max_tip) + 1]
        # print(f"Inherited order because it was already ordered: {inherited_order} ")
    elif max_parent and max_parent == previous_max_tip:
        inherited_order = previous_order[:previous_order.index(max_parent) + 1]

        # Include all necessary nodes and their predecessors for proper ordering
        remaining_blocks = [block for block in past(dag, max_tip) if block not in inherited_order]
        required_nodes = set(remaining_blocks)
        for block in remaining_blocks:
            required_nodes.update(dag.predecessors(block))
        # Ensure max_tip and its predecessors are included
        required_nodes.add(max_tip)
        required_nodes.update(dag.predecessors(max_tip))
        remaining_subgraph = dag.subgraph(required_nodes).copy()

        # Compute the order for remaining blocks
        remaining_order = block_level_ordering(remaining_subgraph, max_tip, blue_scores)

        # Extend the inherited order with the remaining order
        inherited_order.extend([block for block in remaining_order if block not in inherited_order])
        # print(f"Inherited order up to previous max parent {max_parent}: {inherited_order}")
    else:
        inherited_order = block_level_ordering(dag, max_tip, blue_scores)
        # print(f"Max tip {max_tip} was not in previous order so did the block level order and that is : {inherited_order} ")

    # print(f"Inherited Order up to Max Tip: {inherited_order}")

    new_order = [block for block in inherited_order]  # Red Blocks were there
    # Consider remaining tips based on scores or alphabetical order for tie-breaking
    remaining_tips = [tip for tip in tips_list if tip not in new_order]
    # remaining_tips_sorted = sorted(remaining_tips, key=lambda x: (-blue_scores.get(x, 0), x))
    remaining_tips_sorted = sorted(remaining_tips, key=lambda x: (-blue_scores.get(x, 0), hash_block(x)))

    for tip in remaining_tips_sorted:
        tip_order = block_level_ordering(dag, tip, blue_scores)
        for block in tip_order:
            if block not in new_order:
                new_order.append(block)

    # Ensure the red blocks are at the end
    new_order = [block for block in new_order if block not in red_set]
    new_order += sorted(red_set, key=lambda x: blue_scores.get(x, 0))
    # print(f"Final Ordered List: {new_order}")

    return new_order


def update_scores(dag, blue_set, red_set, blue_scores):
    """Update scores of all blocks in the DAG based on the current blue and red sets."""
    for block in nx.topological_sort(dag):
        if block == 'G':
            continue
        if block in blue_set:
            blue_score = len(past(dag, block).intersection(blue_set)) + 1  # Include the block itself in the score
        else:
            blue_score = len(past(dag, block).intersection(blue_set))
        blue_scores[block] = blue_score  # Set the blue score of the block


def apply_ghostforge(dag, new_blocks, blue_set, red_set, blue_scores, visualizer, previous_order, miner_id,
                     previous_max_tip, k=3):
    """Apply the J_version protocol to new blocks in the DAG."""

    # Block-Level Coloring and Scoring
    for block in new_blocks:
        if block == 'G':
            continue
        color, score = block_level_coloring_and_scoring(dag, block, red_set, blue_set, blue_scores, k, visualizer,
                                                        miner_id)
        if color == "red":
            red_set.add(block)  # Add block to red set if its color is red

    # DAG-Level Coloring and Ordering
    ordered_list, max_blue_set, previous_max_tip = dag_level_coloring_and_ordering(dag, blue_set, red_set, blue_scores,
                                                                                   k, previous_order, miner_id,
                                                                                   previous_max_tip)

    return ordered_list, blue_set, red_set, blue_scores, previous_max_tip
